### ISSUE TITLE
Working directory issue.

### ISSUE THREAD

**Issue by YuMingLiao** [nmattia/snack#153]
Hi, first of all, snack is so great! I keep facing long compile time issue in haskell-nix way. And snack definitely can save a lot of time.

I try to use snack to run a yesod project. But since its working directory is "/build/extra-files"
So I encounter an error like this:
```
Compiling module Settings
/build/extra-files  --a pwd command I add to see where I am.

Settings.hs:119:23: error:
    * Exception when trying to run compile-time code:
        config/settings.yml: openBinaryFile: does not exist (No such file or directory)
      Code: embedFile configSettingsYml
    * In the untyped splice: $(embedFile configSettingsYml)
    |
119 | configSettingsYmlBS = $(embedFile configSettingsYml)
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

builder for '/nix/store/pffp271rz5rnb2r5jaad8ihaw56xlqzi-Settings.drv' failed with exit code 1

```

My code can't address the config/settings.yml file in my working directory. And I don't have build folder in my /. And making it an absolute path seems not solving the issue. 
Would snack support this?

**Comment by nmattia** [comment]
Interesting! Are those files specified as extra data in the cabal file? Do you have a minimal reproducible example I can play with?

**Comment by YuMingLiao** [comment]
I didn't know there is a data-files field in the cabal file. Let me test it out first.

**Comment by YuMingLiao** [comment]
I followed tests/template-haskell-4 example and successfully solved this issue. It turns out I just need to set extra-directories into my package.nix. Thanks for these tidy template-haskell examples.
