### ISSUE TITLE
support ghci options

### ISSUE THREAD

**Issue by YuMingLiao** [nmattia/snack#157]
$ snack ghci --no-load
Invalid option `--no-load'

**Comment by nmattia** [comment]
Ah! it should be straight forward to extend `Ghci` with the same arguments as `Run`:
https://github.com/nmattia/snack/blob/bdb6061eeda26f6d2c432659baa74d9c4dfc4f39/bin/Snack.hs#L236

and allow `$ snack ghci -- --no-load`

**Comment by zhujinxuan** [comment]
Shall we also allow user to config options in nix as well?
