### ISSUE TITLE
Unable to link when main module is not Main

### ISSUE THREAD

**Issue by zhujinxuan** [nmattia/snack#161]
Environment: NIxpkgs on Mac 10.15.1

When I am compiling a test with snack, with package.nix as 
```
let
  lib =
    { src = ./src;
      dependencies = ["containers" "recursion-schemes" "text"];
    };
in
  { main = "Spec";
    src = ./test;
    packages = [ lib ];
    extensions = [ "OverloadedStrings"];
  }
```
where the main module is directed to Spec.  The compile will fail with
> clang-5.0: error: no such file or directory: '/nix/store/91pmjg83d7wx6pgl4ccvjc729qwpg3ji-Spec/Main.o'

I think it related to 
https://github.com/nmattia/snack/blob/ddc5135b727543a8f691cb4e0c092d5ca26ca3b6/snack-lib/build.nix#L25

Perhaps we need to change the `Main.o` with `mainModSpec.o`?

**Comment by nmattia** [comment]
I remember having lots of issues around this, GHC has some weird semantics when it comes to specifying the main module name. Did you try the fix you suggest?

**Comment by zhujinxuan** [comment]
I will have a try this weekend (still learning nix at this moment)
