### ISSUE TITLE
Linker phase error

### ISSUE THREAD

**Issue by thebrodmann** [nmattia/snack#174]
Trying to install snack on macOS 10.15.2 but involving with the following error:

```
installing 'snack'
building '/nix/store/5g87k7f6jczvv71nwgps3vja9dg8b9rx-import-parser.drv'...
Linking /nix/store/qx924gs8c2p8nmaf65m7hfjm9dibwwxl-import-parser ...
impure path `/System/Volumes/Data/nix/store/w5lvws91n0v30yay4rbxxn7jbwv3rd0v-clang-5.0.2/lib/libLTO.dylib' used in link
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
`cc' failed in phase `Linker'. (Exit code: 1)
builder for '/nix/store/5g87k7f6jczvv71nwgps3vja9dg8b9rx-import-parser.drv' failed with exit code 1
cannot build derivation '/nix/store/lf77dljrfr9bw3rij0jp66z5j4j89hkh-dependencies-json.drv': 1 dependencies couldn't be built
error: build of '/nix/store/lf77dljrfr9bw3rij0jp66z5j4j89hkh-dependencies-json.drv' failed
(use '--show-trace' to show detailed location information)
```

**Comment by nmattia** [comment]
Hi @thebrodmann ! What macOS version are you using, and how are you installing snack?

**Comment by thebrodmann** [comment]
> What macOS version are you using

macOS Catalina 10.15.2

> how are you installing snack

I tried both ways (with niv and globally) but the above output is the output of the following command:

```bash
nix-env -iA snack-exe -f https://github.com/nmattia/snack/tarball/master
```

**Comment by nmattia** [comment]
Ok, I don't have a Darwin machine ATM, I'll try to reproduce on Monday. Thanks for pointing this out!

**Comment by nmattia** [comment]
Actually, after having a better look at what you posted, I think I know what's happening. I'm guessing you had to workaround the Catalina issues and have setup the nix store in `/System/Volumes/Data/nix`. I doubt this is a snack-specific issues, and I believe you'll hit this whenever you try to link something locally.

This error is thrown here: https://github.com/NixOS/nixpkgs/blob/d9319e8e8725a43e7fa1329cddeef61cd61081b3/pkgs/build-support/bintools-wrapper/ld-wrapper.sh#L44

This is a failsafe to make sure you don't link against stuff located in arbitrary places on your filesystem.

@thebrodmann could you try the workarounds mentioned here? https://github.com/NixOS/nixpkgs/issues/16298

**Comment by thebrodmann** [comment]
OMG, thank you. You’re so helpful.
By replacing symlink with bind mount the problem has been fixed.
