### ISSUE TITLE
CPP doesn't work. Failed to find cabal_macro.h

### ISSUE THREAD

**Issue by YuMingLiao** [nmattia/snack#183]
```
/nix/store/zbm66a1xn7622p3qwfml2d2nawlmn1z9-tutd.hs/tutd.hs:20:0: error:                                                            
     error: missing binary operator before token "("
       20 | #if MIN_VERSION_megaparsec(6,0,0)
          |
   |
20 | #if MIN_VERSION_megaparsec(6,0,0)

```
It seems ghc failed to discover proper version from cabal_macros.h

[On stackoverflow, It](https://stackoverflow.com/questions/12546757/how-do-i-use-cabals-min-version-and-other-macros-with-ghci/12546758) says:
`The cabal build command generates the file dist/build/autogen/cabal_macros.h, which contains all the definitions you need. In order to include that file in a ghc invocation, you'll need the flags -optP-include [-optPdist/build/autogen/cabal_macros.h.`

However, it seems [a feature that generate cabal_marco.h only](https://github.com/haskell/cabal/issues/2209) has not provided yet.

That's the investigation for now.

**Comment by YuMingLiao** [comment]
Handwriting a cabal_macros.h and adding "-optP-include -optPcabal_macros.h" to `ghcOpts` should suffice.

**Comment by nmattia** [comment]
Right, snack does not support cabal-style macros, it works directly with GHC. That's the best solution for now.
