### ISSUE TITLE
Confusing error if --package-yaml argument isn't a valid Nix path literal

### ISSUE THREAD

**Issue by pikajude** [nmattia/snack#37]
```
$ snack ghci -p package.yaml
...lots of base64
' --arg packageYaml package.yaml
exit status: 1
stderr: error: undefined variable 'package' at (string):1:1
```

Looks like the argument to `-p` is just passed verbatim to Nix, limiting it to valid Nix path literals (which `./package.yaml` happens to be). I'd like it here if relative path names were resolved according to `$PWD`, like they are with most Unix tools, and turned into proper paths.

**Comment by nmattia** [comment]
Good idea, will do
