### ISSUE TITLE
ghci not working with 18.09 nixpkgs

### ISSUE THREAD

**Issue by disassembler** [nmattia/snack#65]
I opened a PR #64 but snack ghci isn't working on my project with 18.09 nixpkgs. I'm not sure if it works with stock master, because the main reason I upgraded was `servant-auth-server` is broken in the version with the current pinned nixpkgs.

```
<no location info>: error:
    module ‘main:Api.User’ is defined in multiple files: /home/sam/scratch/servant-persistent/src/Api/User.hs
                                                         /home/sam/scratch/servant-persistent/src/Api/User.hs
```

Here's my snack.nix: https://github.com/disassembler/servant-persistent/blob/master/snack.nix

**Comment by nmattia** [comment]
Indeed. Using #66 I'm able to run `snack ghci` succesfully in https://github.com/disassembler/servant-persistent/blob/master/snack.nix (after removing the dependency on `servant-auth-server`).
